### PR TITLE
adding the depends for Stations

### PR DESCRIPTION
**Pull request by Alonzo-Coeus**
You asked for it. I will be off for the weekend so I will not be available until sunday.

### CODE REVIEW

**Comment by martriay** [comment]
Whoops!
image

**Comment by Alonzo-Coeus** [comment]
martriay any idea on how to fix it other than whoops?

**Comment by Alonzo-Coeus** [comment]
issues have been resolved. awaiting review from a member.

**Comment by martriay** [comment]
Considering that:
- this introduces fixed behavior to tile (0, 0) while scripting is off-protocol right now
- as it breaks the protocol (content can't be exported to a .lnd) it can't be ported to future versions
- mobility within Decentraland is undecided, teleporting is for development purposes

i'm closing this PR. I do feel I have to thank you for the efforts and say that this station is pretty awesome, would totally love for it to be published as normal content.

**Pull request closed without merging**
